# Generated by Django 2.2.12 on 2021-02-27 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='novelmessage',
            name='novel_num',
        ),
        migrations.RemoveField(
            model_name='noveltag',
            name='number',
        ),
        migrations.RemoveField(
            model_name='numtotag',
            name='num',
        ),
        migrations.RemoveField(
            model_name='numtotag',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
        migrations.RemoveField(
            model_name='usertosc',
            name='number',
        ),
        migrations.RemoveField(
            model_name='usertosc',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Novel',
        ),
        migrations.DeleteModel(
            name='NovelMessage',
        ),
        migrations.DeleteModel(
            name='NovelTag',
        ),
        migrations.DeleteModel(
            name='NumToTag',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserToSc',
        ),
    ]
