# Generated by Django 2.2.12 on 2021-02-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('mail', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='电子邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
    ]
