# Generated by Django 3.1.6 on 2021-02-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='电子邮箱'),
        ),
    ]
