# Generated by Django 3.1.6 on 2021-02-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0002_auto_20210205_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('nickname', models.CharField(max_length=5, verbose_name='用户名')),
                ('collection', models.CharField(default='', max_length=100, verbose_name='收藏')),
                ('user_type', models.CharField(default='2', max_length=100, verbose_name='收藏')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('user_vip', models.CharField(default='', max_length=20, verbose_name='vip状态')),
                ('user_vip_time', models.DateTimeField(null=True)),
                ('mail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register_and_login.user')),
            ],
        ),
    ]
