# Generated by Django 3.1.6 on 2021-02-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_and_login', '0003_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_type',
            field=models.CharField(default='2', max_length=100, verbose_name='用户类型'),
        ),
    ]
