# Generated by Django 2.2.12 on 2021-02-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel1', '0003_auto_20210225_1652'),
        ('register_and_login', '0004_auto_20210215_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='mail',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
