# Generated by Django 3.1.6 on 2021-02-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelcontent',
            name='novelsections',
        ),
        migrations.RemoveField(
            model_name='novelmessage',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='novelsections',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='noveltag',
            name='novel',
        ),
        migrations.DeleteModel(
            name='Novel',
        ),
        migrations.DeleteModel(
            name='NovelContent',
        ),
        migrations.DeleteModel(
            name='NovelMessage',
        ),
        migrations.DeleteModel(
            name='NovelSections',
        ),
        migrations.DeleteModel(
            name='NovelTag',
        ),
    ]
