# Generated by Django 2.2.12 on 2021-02-24 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_and_login', '0004_auto_20210215_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Shoucang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel', models.ManyToManyField(to='novel1.Novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_and_login.User')),
            ],
        ),
        migrations.CreateModel(
            name='NovelTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60, verbose_name='标签')),
                ('novel', models.ManyToManyField(to='novel1.Novel')),
            ],
        ),
        migrations.CreateModel(
            name='NovelSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='章节标题')),
                ('content_id', models.IntegerField(verbose_name='对应小说章节数')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='novel1.Novel')),
            ],
        ),
        migrations.CreateModel(
            name='NovelMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('introduce', models.CharField(max_length=999, verbose_name='介绍')),
                ('up', models.IntegerField(default=188, verbose_name='点赞')),
                ('serialize', models.BooleanField(default=True, verbose_name='连载状态')),
                ('vip_type', models.BooleanField(default=False, verbose_name='vip可阅读')),
                ('cover', models.ImageField(upload_to='cover', verbose_name='封面')),
                ('novel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='novel1.Novel')),
            ],
        ),
        migrations.CreateModel(
            name='NovelContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('novelsections', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='novel1.NovelSections')),
            ],
        ),
    ]
