# Generated by Django 2.2.12 on 2021-02-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelmessage',
            name='up',
            field=models.IntegerField(default=628, verbose_name='点赞'),
        ),
    ]
