# Generated by Django 2.2.12 on 2021-02-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel1', '0002_auto_20210225_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelcontent',
            name='novelsections',
        ),
        migrations.RemoveField(
            model_name='novelmessage',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='novelsections',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='noveltag',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='shoucang',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='shoucang',
            name='user',
        ),
        migrations.DeleteModel(
            name='Novel',
        ),
        migrations.DeleteModel(
            name='NovelContent',
        ),
        migrations.DeleteModel(
            name='NovelMessage',
        ),
        migrations.DeleteModel(
            name='NovelSections',
        ),
        migrations.DeleteModel(
            name='NovelTag',
        ),
        migrations.DeleteModel(
            name='Shoucang',
        ),
    ]
