# Generated by Django 2.2.12 on 2021-02-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelmessage',
            name='novel_num',
        ),
        migrations.RemoveField(
            model_name='noveltag',
            name='number',
        ),
        migrations.RemoveField(
            model_name='numtotag',
            name='num',
        ),
        migrations.RemoveField(
            model_name='numtotag',
            name='tags',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranks.Novel'),
        ),
        migrations.DeleteModel(
            name='Novel',
        ),
        migrations.DeleteModel(
            name='NovelMessage',
        ),
        migrations.DeleteModel(
            name='NovelTag',
        ),
        migrations.DeleteModel(
            name='NumToTag',
        ),
    ]
