# Generated by Django 2.2.12 on 2021-02-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20210225_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
