# Generated by Django 2.2.12 on 2021-02-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToSc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranks.Novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranks.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=100, verbose_name='小说章节')),
                ('content', models.TextField(verbose_name='单章内容')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranks.Novel')),
            ],
        ),
        migrations.AddField(
            model_name='novel',
            name='user',
            field=models.ManyToManyField(related_name='user_novel', through='ranks.UserToSc', to='ranks.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.ManyToManyField(related_name='user_novel', through='ranks.UserToSc', to='ranks.Novel', verbose_name='num1'),
        ),
    ]
