# Generated by Django 2.2.12 on 2021-02-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0003_auto_20210224_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertosc',
            old_name='num1',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='user',
        ),
        migrations.AddField(
            model_name='novel',
            name='mail',
            field=models.ManyToManyField(through='ranks.UserToSc', to='ranks.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.ManyToManyField(through='ranks.UserToSc', to='ranks.Novel', verbose_name='num1'),
        ),
    ]
