# Generated by Django 2.2.12 on 2021-02-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0004_auto_20210224_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, null=True, verbose_name='密码'),
        ),
    ]
