# Generated by Django 2.2.12 on 2021-02-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0005_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
